# Generated by Django 4.2.11 on 2024-09-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={'verbose_name': 'Жанр кинопроизведения', 'verbose_name_plural': 'Жанры кинопроизведений'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'verbose_name': 'Персоналия киинопроизведения', 'verbose_name_plural': 'Персоналии киинопроизведений'},
        ),
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='film_work',
            new_name='film_work_id',
        ),
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(blank=True, verbose_name='creation_date'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'Movies'), ('ТВ-шоу', 'Tv Show')], verbose_name='type'),
        ),
    ]
