# Generated by Django 4.2.11 on 2024-09-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_film_work_id_genrefilmwork_film_work_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='film_work_id',
            new_name='film_work',
        ),
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='person_id',
            new_name='person',
        ),
    ]
